### ISSUE TITLE
Pre selected trim

### ISSUE THREAD

**Issue by ghimireprashant** [AndreasVerhoeven/VideoTrimmerControl#2]
how to pre select trim?
for example i trim that asset before and want to re edit my trim.

**Comment by AndreasVerhoeven** [comment]
You assign the __original__ AVAsset to the control and then set the `selectedRange` field to the trim you want to show

**Comment by ghimireprashant** [comment]
thanks mate. is there any to display actual trim video frame in video player?
like default trimmer in photo ass show trimmer with  progress in actual video

**Comment by AndreasVerhoeven** [comment]
You can take a look at the bundled example which more or less does that
