### ISSUE TITLE
Issue when dragging leading & trailing grabber

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [AndreasVerhoeven/VideoTrimmerControl#3]
`progressIndicator` position is getting changed when I `end dragging leading & trailing grabber`.

Can you please help me with this minor issue? Your assistance would be greatly appreciated.

I have been using your wonderful utility tool and it has saved me a lot of time.

If you are able to provide remote assistance, please contact me at rashesh.bosamiya@gmail.com via FaceTime, AppleID, or Email. Thank you for your consideration.

Sincerely,
Rashesh

**Comment by AndreasVerhoeven** [comment]
Can you upload a video of the issue?

**Comment by Rashesh-Bosamiya** [comment]
Sure, give me a moment & thanks for quick response

**Comment by Rashesh-Bosamiya** [comment]
Here is the video

https://user-images.githubusercontent.com/19154948/217837503-830d5d3b-a0b6-4582-ae19-fd862e3c9b7b.mov

**Comment by Rashesh-Bosamiya** [comment]
you can see the progress indicator always comes to certain position after I lift either side of grabber.

**Comment by AndreasVerhoeven** [comment]
> you can see the progress indicator always comes to certain position after I lift either side of grabber.

Do you reset the current position of the video player when trimming ends? The trimmer doesn't control the video position: that should all be done by your code.

**Comment by Rashesh-Bosamiya** [comment]
I am not resetting current position, I am utilising your sample code only from github.

**Comment by Rashesh-Bosamiya** [comment]
If you would like to take a quick screen-sharing session using Mac's native screen-sharing utility, here is my Apple ID [rashesh.bosamiya@gmail.com] to connect. With this utility, you can easily view & control my screen, allowing for a more efficient and effective collaboration.

At your convenience would be ideal too.

![Screenshot 2023-02-09 at 7 51 54 PM](https://user-images.githubusercontent.com/19154948/217844917-dd416ba4-a172-4e86-9681-11f8fae09864.png)

**Comment by AndreasVerhoeven** [comment]
> If you would like to take a quick screen-sharing session using Mac's native screen-sharing utility, here is my Apple ID [[rashesh.bosamiya@gmail.com](mailto:rashesh.bosamiya@gmail.com)] to connect. With this utility, you can easily view & control my screen, allowing for a more efficient and effective collaboration.
> 
> At your convenience would be ideal too.
> 
> ![Screenshot 2023-02-09 at 7 51 54 PM](https://user-images.githubusercontent.com/19154948/217844917-dd416ba4-a172-4e86-9681-11f8fae09864.png)

This is a free package; if you want commercial support I can provide that for a fee.

**Comment by Rashesh-Bosamiya** [comment]
@AndreasVerhoeven, Not looking for commercial support.

Whatsoever, are you able to at least understood the issue by the video I provided?
The progress indicator changes its position when either side of grabber ends gesture.
